Zqs 1104 new pauli operator data structure
zapatacomputing/orquestra-vqa pull request #21
Opened 2022-08-02 17:41 UTC by laurgao

## Description

Include description of feature this PR introduces or a bug that it fixes. Include the following information:

- Context: why is it needed? In case of bug, what was the cause for the bug?
- Concise description of the implemented solution.
- If any dependencies are added, list them and justify why they are needed.

## Please verify that you have completed the following steps

- [ ] I have self-reviewed my code.
- [ ] I have included test cases validating introduced feature/fix.
- [ ] I have updated documentation.

2022-08-05 10:07 UTC, mstechly requested changes

2022-08-05 13:14 UTC, laurgao commented on tests/orquestra/vqa/ansatz/qaoa_warm_start_test.py
> +        new_cost_hamiltonian = PauliSum("Z0 + -1*Z1")
This syntax is currently not supported in `PauliSum` :/ Konrad made a story to add it

2022-08-05 13:27 UTC, laurgao commented on src/orquestra/vqa/ansatz/qaoa_farhi.py
> +        return count_qubits(self._cost_hamiltonian)
that is a great idea... much nicer than importing `count_qubits` all the time

2022-08-05 13:27 UTC, laurgao commented on src/orquestra/vqa/estimation/context_selection.py
> +            assert isinstance(product, PauliTerm)
mypy issues, `PauliTerm.__mul__` can return either a `PauliTerm` or a `PauliSum`

2022-08-05 13:29 UTC, laurgao commented on tests/orquestra/vqa/ansatz/qaoa_farhi_test.py
> +        new_cost_hamiltonian = PauliTerm("Z0*Z1*Z2")
this test was added to make sure that it works with the `PauliTerm` class

2022-08-05 13:29 UTC, laurgao commented on tests/orquestra/vqa/ansatz/qaoa_warm_start_test.py
> -        target_unitary = create_target_unitary(thetas, number_of_layers)
it's defined in the line after:
`target_unitary = create_1_qubit_target_unitary(thetas, number_of_layers)`

2022-08-05 13:42 UTC, laurgao commented on src/orquestra/vqa/opt/recursive_qaoa.py
> +        coefficient = term.coefficient
Later we may or may not reassign the variable `coefficient` depending on the sign of the largest expectation value so I think it's better to keep it

2022-08-05 13:44 UTC, laurgao commented on src/orquestra/vqa/grouping/_grouping.py
> -def _group_comeasureable_terms_greedy_sorted(
It's a private method that's not used anywhere in this file or in this repo so I thought it was unnecessary🤷 But then I realized it's used in `orquestra-vqa-internal` so I'll add it back

2022-08-05 14:08 UTC, mstechly commented on src/orquestra/vqa/ansatz/qaoa_farhi.py
> +        return count_qubits(self._cost_hamiltonian)
We could do this as a part of another story though!

2022-08-05 14:09 UTC, mstechly commented on src/orquestra/vqa/grouping/_grouping.py
> -def _group_comeasureable_terms_greedy_sorted(
If it's used outside of this package please make it public :)

2022-08-05 14:10 UTC, mstechly commented on tests/orquestra/vqa/ansatz/qaoa_farhi_test.py
> +        new_cost_hamiltonian = PauliTerm("Z0*Z1*Z2")
👌

2022-08-05 14:10 UTC, mstechly commented on tests/orquestra/vqa/ansatz/qaoa_warm_start_test.py
> +        new_cost_hamiltonian = PauliSum("Z0 + -1*Z1")
👌

2022-08-05 14:55 UTC, laurgao commented on src/orquestra/vqa/ansatz/qaoa_farhi.py
> +        return count_qubits(self._cost_hamiltonian)
Sounds good, we could probably do it when we get rid of openfermion because we'll be getting rid of the `count_qubits` function in openfermion

2022-08-09 14:18 UTC, mstechly approved these changes

2022-08-09 15:09 UTC, laurgao commented on src/orquestra/vqa/grouping/_grouping.py
> +    return PauliSum([term for term in group.terms if not term.is_constant])
Yup I agree, but I can't really think of a better way. Do you have any ideas?

2022-08-09 15:11 UTC, merged